//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type BankingDetails struct {
	StudentID     int32 `sql:"primary_key"`
	BankName      string
	BranchName    string
	AccountType   BankAccountType
	AccountNumber []byte
	CreatedAt     time.Time
	UpdatedAt     *time.Time
}
