//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Payments struct {
	PaymentID   uuid.UUID `sql:"primary_key"`
	StudentID   int32
	PeriodStart time.Time
	PeriodEnd   time.Time
	HoursWorked float64
	GrossAmount float64
	ProcessedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   *time.Time
}
