//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/google/uuid"
)

type Users struct {
	UserID          uuid.UUID `sql:"primary_key"`
	EmailAddress    string
	Password        string
	Role            Roles
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       *time.Time
	EmailVerifiedAt *time.Time
	FirstName       string
	LastName        string
}
