# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  BACKEND_DIR: ./apps/backend
  FRONTEND_DIR: ./apps/frontend
  SCHEDULER_DIR: ./apps/scheduler
  TRANSCRIPT_DIR: ./apps/transcript_extraction_function
  MIGRATIONS_DIR: ./migrations
  DATABASE_URL: "postgres://helpdesk:helpdesk_local@localhost:5432/helpdesk?sslmode=disable"
  COMPOSE_FILE: docker-compose.local.yml

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  # Setup
  install:
    desc: Install all dependencies
    cmds:
      - task: install:backend
      - task: install:frontend

  install:backend:
    desc: Install backend dependencies
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go mod download

  install:frontend:
    desc: Install frontend dependencies
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm install

  # Build
  build:
    desc: Build all projects
    cmds:
      - task: build:backend
      - task: build:frontend

  build:backend:
    desc: Build the backend binary
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go build -o bin/server ./cmd/server

  build:frontend:
    desc: Build the frontend
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm build

  # Docker
  start:
    desc: Start all services with Docker Compose
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d

  build:
    desc: Start all services with Docker Compose
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d --build

  stop:
    desc: Stop all services
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} down

  logs:
    desc: View service logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs -f

  # Testing
  test:
    desc: Run all tests
    cmds:
      - task: test:backend
      - task: test:scheduler
      - task: test:transcript
      - task: test:frontend

  test:backend:
    desc: Run backend tests
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go test ./...

  test:scheduler:
    desc: Run scheduler tests
    dir: "{{.SCHEDULER_DIR}}"
    cmds:
      - .venv/bin/python -m pytest tests/ -v

  test:transcript:
    desc: Run transcript extraction tests
    dir: "{{.TRANSCRIPT_DIR}}"
    cmds:
      - .venv/bin/python -m pytest tests/ -v

  test:frontend:
    desc: Run frontend tests
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm test

  # Migrations
  migrate:up:
    desc: Run all pending migrations
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" up

  migrate:down:
    desc: Rollback the last migration
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" down 1

  migrate:reset:
    desc: Rollback all migrations
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" down -all

  migrate:create:
    desc: "Create a new migration (usage: task migrate:create -- name)"
    cmds:
      - migrate create -ext sql -dir {{.MIGRATIONS_DIR}} -seq {{.CLI_ARGS}}

  generate:models:
    desc: Generate Go models from database schema using jet
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - jet -dsn={{.DATABASE_URL}} -schema=auth -path=./internal/infrastructure/models
      - jet -dsn={{.DATABASE_URL}} -schema=schedule -path=./internal/infrastructure/models

  # Database
  db:start:
    desc: Start the PostgreSQL database
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d postgres
      - |
        echo "Waiting for PostgreSQL to be ready..."
        for i in $(seq 1 30); do
          if docker compose -f {{.COMPOSE_FILE}} exec postgres pg_isready -U helpdesk -d helpdesk -q 2>/dev/null; then
            echo "PostgreSQL is ready."
            exit 0
          fi
          sleep 1
        done
        echo "Timed out waiting for PostgreSQL."
        exit 1

  db:studio:
    desc: Open Drizzle Studio to view the database
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm db:studio

  db:reset:
    desc: Drop and recreate the database, run migrations, start services and seed
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} down -v
      - task: db:start
      - task: migrate:up
      - docker compose -f {{.COMPOSE_FILE}} up -d
      - |
        echo "Waiting for backend to be ready..."
        for i in $(seq 1 60); do
          if curl -sf http://localhost:8080/health >/dev/null 2>&1; then
            echo "Backend is ready."
            exit 0
          fi
          sleep 1
        done
        echo "Timed out waiting for backend."
        exit 1
      - task: db:seed

  db:seed:
    desc: Seed the database with dev data (requires backend to be running)
    cmds:
      - ./scripts/seed_dev.sh

  # Visualize
  visualize:
    desc: "Show shifts, schedule grid, and availability (usage: task visualize [-- <id>])"
    cmds:
      - ./scripts/visualize.sh all {{.CLI_ARGS}}

  visualize:shifts:
    desc: Show shift templates as a weekly grid
    cmds:
      - ./scripts/visualize.sh shifts

  visualize:schedule:
    desc: "Show a schedule grid (usage: task visualize:schedule [-- <id>], omit id to list)"
    cmds:
      - ./scripts/visualize.sh schedule {{.CLI_ARGS}}

  visualize:availability:
    desc: "Show assistant availability for a schedule (usage: task visualize:availability -- <id>)"
    cmds:
      - ./scripts/visualize.sh availability {{.CLI_ARGS}}
