# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  BACKEND_DIR: ./backend
  FRONTEND_DIR: ./frontend
  SCHEDULER_DIR: ./scheduler
  MIGRATIONS_DIR: ./migrations
  DATABASE_URL: "postgres://helpdesk:helpdesk_local@localhost:5432/helpdesk?sslmode=disable"
  COMPOSE_FILE: docker-compose.local.yml

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  # Setup
  install:
    desc: Install all dependencies
    cmds:
      - task: install:backend
      - task: install:frontend

  install:backend:
    desc: Install backend dependencies
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go mod download

  install:frontend:
    desc: Install frontend dependencies
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm install

  # Development
  dev:
    desc: Run both backend and frontend in development mode
    deps:
      - db:start
    cmds:
      - task --parallel dev:backend dev:frontend

  dev:backend:
    desc: Run the backend in development mode
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go run ./cmd/server

  dev:frontend:
    desc: Run the frontend in development mode
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm dev

  # Build
  build:
    desc: Build all projects
    cmds:
      - task: build:backend
      - task: build:frontend

  build:backend:
    desc: Build the backend binary
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go build -o bin/server ./cmd/server

  build:frontend:
    desc: Build the frontend
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm build

  # Docker
  start:
    desc: Start all services with Docker Compose
    cmds:
      - docker-compose -f docker-compose.local.yml up -d --build

  stop:
    desc: Stop all services
    cmds:
      - docker-compose -f docker-compose.local.yml down

  logs:
    desc: View service logs
    cmds:
      - docker-compose -f docker-compose.local.yml logs -f

  # Testing
  test:
    desc: Run all tests
    cmds:
      - task: test:backend
      - task: test:scheduler
      - task: test:frontend

  test:backend:
    desc: Run backend tests
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go test ./...

  test:scheduler:
    desc: Run scheduler tests
    dir: "{{.SCHEDULER_DIR}}"
    cmds:
      - .venv/bin/python -m pytest tests/ -v

  test:frontend:
    desc: Run frontend tests
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm test

  test:coverage:
    desc: Run backend tests with coverage
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go test -cover ./...

  # Migrations
  "migrate:up":
    desc: Run all pending migrations
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" up

  "migrate:down":
    desc: Rollback the last migration
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" down 1

  "migrate:reset":
    desc: Rollback all migrations
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" down -all

  "migrate:create":
    desc: "Create a new migration (usage: task migrate:create -- name)"
    cmds:
      - migrate create -ext sql -dir {{.MIGRATIONS_DIR}} -seq {{.CLI_ARGS}}

  "generate:models":
    desc: Generate Go models from database schema using jet
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - jet -dsn={{.DATABASE_URL}} -schema=auth -path=./internal/infrastructure/models
      - jet -dsn={{.DATABASE_URL}} -schema=schedule -path=./internal/infrastructure/models

  # Database
  "db:start":
    desc: Start the PostgreSQL database
    cmds:
      - docker-compose -f docker-compose.local.yml up -d postgres
      - docker-compose -f docker-compose.local.yml exec postgres pg_isready -U helpdesk -d helpdesk --timeout=30

  "db:studio":
    desc: Open Drizzle Studio to view the database
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm db:studio

  "db:reset":
    desc: Drop and recreate the database
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} down -v
      - task: db:start
      - task: migrate:up
