//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Schedules struct {
	ScheduleID           uuid.UUID `sql:"primary_key"`
	Title                string
	IsActive             bool
	Assignments          string // This is used to store the assignments of students for a given schedule. { [student_id:int] { [0...4]: []int } }
	AvailabilityMetadata string // This stores the availabilities that were used to generate the schedule. { [student_id:int]: map[int][]int }
	CreatedAt            time.Time
	CreatedBy            uuid.UUID
	UpdatedAt            *time.Time
	ArchivedAt           *time.Time
	EffectiveFrom        time.Time
	EffectiveTo          *time.Time
	GenerationID         *uuid.UUID
	SchedulerMetadata    *string // Optimizer results: {objective_value, assistant_hours, shortfalls, solver_status}
}
