//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

// Audit log for schedule generation requests.
type ScheduleGenerations struct {
	ID              uuid.UUID `sql:"primary_key"`
	ScheduleID      *uuid.UUID
	ConfigID        uuid.UUID
	Status          string
	RequestPayload  *string
	ResponsePayload *string
	ErrorMessage    *string
	StartedAt       *time.Time
	CompletedAt     *time.Time
	CreatedAt       time.Time
	CreatedBy       uuid.UUID
}
