//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

// Defines shift slots that need to be staffed. These are inputs to the scheduler.
type ShiftTemplates struct {
	ID            uuid.UUID `sql:"primary_key"`
	Name          string
	DayOfWeek     int32
	StartTime     time.Time
	EndTime       time.Time
	MinStaff      int32
	MaxStaff      *int32
	CourseDemands string // Array of {course_code: string, tutors_required: int, weight: float}
	IsActive      bool
	CreatedAt     time.Time
	UpdatedAt     *time.Time
}
