//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ClockInCodes = newClockInCodesTable("schedule", "clock_in_codes", "")

type clockInCodesTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	Code      postgres.ColumnString
	ExpiresAt postgres.ColumnTimestampz
	CreatedAt postgres.ColumnTimestampz
	CreatedBy postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ClockInCodesTable struct {
	clockInCodesTable

	EXCLUDED clockInCodesTable
}

// AS creates new ClockInCodesTable with assigned alias
func (a ClockInCodesTable) AS(alias string) *ClockInCodesTable {
	return newClockInCodesTable(a.SchemaName(), a.TableName(), alias)
}

// FromSchema creates new ClockInCodesTable with assigned schema name
func (a ClockInCodesTable) FromSchema(schemaName string) *ClockInCodesTable {
	return newClockInCodesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ClockInCodesTable with assigned table prefix
func (a ClockInCodesTable) WithPrefix(prefix string) *ClockInCodesTable {
	return newClockInCodesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ClockInCodesTable with assigned table suffix
func (a ClockInCodesTable) WithSuffix(suffix string) *ClockInCodesTable {
	return newClockInCodesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newClockInCodesTable(schemaName, tableName, alias string) *ClockInCodesTable {
	return &ClockInCodesTable{
		clockInCodesTable: newClockInCodesTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newClockInCodesTableImpl("", "excluded", ""),
	}
}

func newClockInCodesTableImpl(schemaName, tableName, alias string) clockInCodesTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		CodeColumn      = postgres.StringColumn("code")
		ExpiresAtColumn = postgres.TimestampzColumn("expires_at")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		CreatedByColumn = postgres.StringColumn("created_by")
		allColumns      = postgres.ColumnList{IDColumn, CodeColumn, ExpiresAtColumn, CreatedAtColumn, CreatedByColumn}
		mutableColumns  = postgres.ColumnList{CodeColumn, ExpiresAtColumn, CreatedAtColumn, CreatedByColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return clockInCodesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Code:      CodeColumn,
		ExpiresAt: ExpiresAtColumn,
		CreatedAt: CreatedAtColumn,
		CreatedBy: CreatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
