//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TimeLogs = newTimeLogsTable("schedule", "time_logs", "")

type timeLogsTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	StudentID      postgres.ColumnInteger
	EntryAt        postgres.ColumnTimestampz
	ExitAt         postgres.ColumnTimestampz
	CreatedAt      postgres.ColumnTimestampz
	Longitude      postgres.ColumnFloat
	Latitude       postgres.ColumnFloat
	DistanceMeters postgres.ColumnFloat // A pre-calculated distance based on the longitude and latitude to be later used to flag suspicious entries.

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TimeLogsTable struct {
	timeLogsTable

	EXCLUDED timeLogsTable
}

// AS creates new TimeLogsTable with assigned alias
func (a TimeLogsTable) AS(alias string) *TimeLogsTable {
	return newTimeLogsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TimeLogsTable with assigned schema name
func (a TimeLogsTable) FromSchema(schemaName string) *TimeLogsTable {
	return newTimeLogsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TimeLogsTable with assigned table prefix
func (a TimeLogsTable) WithPrefix(prefix string) *TimeLogsTable {
	return newTimeLogsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TimeLogsTable with assigned table suffix
func (a TimeLogsTable) WithSuffix(suffix string) *TimeLogsTable {
	return newTimeLogsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTimeLogsTable(schemaName, tableName, alias string) *TimeLogsTable {
	return &TimeLogsTable{
		timeLogsTable: newTimeLogsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newTimeLogsTableImpl("", "excluded", ""),
	}
}

func newTimeLogsTableImpl(schemaName, tableName, alias string) timeLogsTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		StudentIDColumn      = postgres.IntegerColumn("student_id")
		EntryAtColumn        = postgres.TimestampzColumn("entry_at")
		ExitAtColumn         = postgres.TimestampzColumn("exit_at")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		LongitudeColumn      = postgres.FloatColumn("longitude")
		LatitudeColumn       = postgres.FloatColumn("latitude")
		DistanceMetersColumn = postgres.FloatColumn("distance_meters")
		allColumns           = postgres.ColumnList{IDColumn, StudentIDColumn, EntryAtColumn, ExitAtColumn, CreatedAtColumn, LongitudeColumn, LatitudeColumn, DistanceMetersColumn}
		mutableColumns       = postgres.ColumnList{StudentIDColumn, EntryAtColumn, ExitAtColumn, CreatedAtColumn, LongitudeColumn, LatitudeColumn, DistanceMetersColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return timeLogsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		StudentID:      StudentIDColumn,
		EntryAt:        EntryAtColumn,
		ExitAt:         ExitAtColumn,
		CreatedAt:      CreatedAtColumn,
		Longitude:      LongitudeColumn,
		Latitude:       LatitudeColumn,
		DistanceMeters: DistanceMetersColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
