//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var BankingDetails = newBankingDetailsTable("auth", "banking_details", "")

type bankingDetailsTable struct {
	postgres.Table

	// Columns
	StudentID     postgres.ColumnInteger
	BankName      postgres.ColumnString
	BranchName    postgres.ColumnString
	AccountType   postgres.ColumnString
	AccountNumber postgres.ColumnBytea

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type BankingDetailsTable struct {
	bankingDetailsTable

	EXCLUDED bankingDetailsTable
}

// AS creates new BankingDetailsTable with assigned alias
func (a BankingDetailsTable) AS(alias string) *BankingDetailsTable {
	return newBankingDetailsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BankingDetailsTable with assigned schema name
func (a BankingDetailsTable) FromSchema(schemaName string) *BankingDetailsTable {
	return newBankingDetailsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BankingDetailsTable with assigned table prefix
func (a BankingDetailsTable) WithPrefix(prefix string) *BankingDetailsTable {
	return newBankingDetailsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BankingDetailsTable with assigned table suffix
func (a BankingDetailsTable) WithSuffix(suffix string) *BankingDetailsTable {
	return newBankingDetailsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBankingDetailsTable(schemaName, tableName, alias string) *BankingDetailsTable {
	return &BankingDetailsTable{
		bankingDetailsTable: newBankingDetailsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newBankingDetailsTableImpl("", "excluded", ""),
	}
}

func newBankingDetailsTableImpl(schemaName, tableName, alias string) bankingDetailsTable {
	var (
		StudentIDColumn     = postgres.IntegerColumn("student_id")
		BankNameColumn      = postgres.StringColumn("bank_name")
		BranchNameColumn    = postgres.StringColumn("branch_name")
		AccountTypeColumn   = postgres.StringColumn("account_type")
		AccountNumberColumn = postgres.ByteaColumn("account_number")
		allColumns          = postgres.ColumnList{StudentIDColumn, BankNameColumn, BranchNameColumn, AccountTypeColumn, AccountNumberColumn}
		mutableColumns      = postgres.ColumnList{BankNameColumn, BranchNameColumn, AccountTypeColumn, AccountNumberColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return bankingDetailsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		StudentID:     StudentIDColumn,
		BankName:      BankNameColumn,
		BranchName:    BranchNameColumn,
		AccountType:   AccountTypeColumn,
		AccountNumber: AccountNumberColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
