//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Payments = newPaymentsTable("auth", "payments", "")

type paymentsTable struct {
	postgres.Table

	// Columns
	PaymentID   postgres.ColumnString
	StudentID   postgres.ColumnInteger
	PeriodStart postgres.ColumnDate
	PeriodEnd   postgres.ColumnDate
	HoursWorked postgres.ColumnFloat
	GrossAmount postgres.ColumnFloat
	ProcessedAt postgres.ColumnTimestampz
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PaymentsTable struct {
	paymentsTable

	EXCLUDED paymentsTable
}

// AS creates new PaymentsTable with assigned alias
func (a PaymentsTable) AS(alias string) *PaymentsTable {
	return newPaymentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PaymentsTable with assigned schema name
func (a PaymentsTable) FromSchema(schemaName string) *PaymentsTable {
	return newPaymentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PaymentsTable with assigned table prefix
func (a PaymentsTable) WithPrefix(prefix string) *PaymentsTable {
	return newPaymentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PaymentsTable with assigned table suffix
func (a PaymentsTable) WithSuffix(suffix string) *PaymentsTable {
	return newPaymentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPaymentsTable(schemaName, tableName, alias string) *PaymentsTable {
	return &PaymentsTable{
		paymentsTable: newPaymentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newPaymentsTableImpl("", "excluded", ""),
	}
}

func newPaymentsTableImpl(schemaName, tableName, alias string) paymentsTable {
	var (
		PaymentIDColumn   = postgres.StringColumn("payment_id")
		StudentIDColumn   = postgres.IntegerColumn("student_id")
		PeriodStartColumn = postgres.DateColumn("period_start")
		PeriodEndColumn   = postgres.DateColumn("period_end")
		HoursWorkedColumn = postgres.FloatColumn("hours_worked")
		GrossAmountColumn = postgres.FloatColumn("gross_amount")
		ProcessedAtColumn = postgres.TimestampzColumn("processed_at")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{PaymentIDColumn, StudentIDColumn, PeriodStartColumn, PeriodEndColumn, HoursWorkedColumn, GrossAmountColumn, ProcessedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{StudentIDColumn, PeriodStartColumn, PeriodEndColumn, HoursWorkedColumn, GrossAmountColumn, ProcessedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = postgres.ColumnList{}
	)

	return paymentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		PaymentID:   PaymentIDColumn,
		StudentID:   StudentIDColumn,
		PeriodStart: PeriodStartColumn,
		PeriodEnd:   PeriodEndColumn,
		HoursWorked: HoursWorkedColumn,
		GrossAmount: GrossAmountColumn,
		ProcessedAt: ProcessedAtColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
