//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Students = newStudentsTable("auth", "students", "")

type studentsTable struct {
	postgres.Table

	// Columns
	StudentID          postgres.ColumnInteger
	EmailAddress       postgres.ColumnString
	FirstName          postgres.ColumnString
	LastName           postgres.ColumnString
	TranscriptMetadata postgres.ColumnString // transcript metadata contains the relevant extracted information from their provided transcripts. It should follow the below structure: { overall_gpa: float; degree_gpa: float; degree_programme: string; courses: []maps[string]float; }
	Availability       postgres.ColumnString // Availability contains a json indicating the availability of a student for each time slot given. The times a represented in 24-hour format. e.g. 8 represents 8 am - 9am { 0: [8...16], . . 4: [8...16] // 24 hr format }
	CreatedAt          postgres.ColumnTimestampz
	UpdatedAt          postgres.ColumnTimestampz
	DeletedAt          postgres.ColumnTimestampz
	AcceptedAt         postgres.ColumnTimestampz
	RejectedAt         postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type StudentsTable struct {
	studentsTable

	EXCLUDED studentsTable
}

// AS creates new StudentsTable with assigned alias
func (a StudentsTable) AS(alias string) *StudentsTable {
	return newStudentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new StudentsTable with assigned schema name
func (a StudentsTable) FromSchema(schemaName string) *StudentsTable {
	return newStudentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new StudentsTable with assigned table prefix
func (a StudentsTable) WithPrefix(prefix string) *StudentsTable {
	return newStudentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new StudentsTable with assigned table suffix
func (a StudentsTable) WithSuffix(suffix string) *StudentsTable {
	return newStudentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newStudentsTable(schemaName, tableName, alias string) *StudentsTable {
	return &StudentsTable{
		studentsTable: newStudentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newStudentsTableImpl("", "excluded", ""),
	}
}

func newStudentsTableImpl(schemaName, tableName, alias string) studentsTable {
	var (
		StudentIDColumn          = postgres.IntegerColumn("student_id")
		EmailAddressColumn       = postgres.StringColumn("email_address")
		FirstNameColumn          = postgres.StringColumn("first_name")
		LastNameColumn           = postgres.StringColumn("last_name")
		TranscriptMetadataColumn = postgres.StringColumn("transcript_metadata")
		AvailabilityColumn       = postgres.StringColumn("availability")
		CreatedAtColumn          = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn          = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn          = postgres.TimestampzColumn("deleted_at")
		AcceptedAtColumn         = postgres.TimestampzColumn("accepted_at")
		RejectedAtColumn         = postgres.TimestampzColumn("rejected_at")
		allColumns               = postgres.ColumnList{StudentIDColumn, EmailAddressColumn, FirstNameColumn, LastNameColumn, TranscriptMetadataColumn, AvailabilityColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, AcceptedAtColumn, RejectedAtColumn}
		mutableColumns           = postgres.ColumnList{EmailAddressColumn, FirstNameColumn, LastNameColumn, TranscriptMetadataColumn, AvailabilityColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, AcceptedAtColumn, RejectedAtColumn}
		defaultColumns           = postgres.ColumnList{}
	)

	return studentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		StudentID:          StudentIDColumn,
		EmailAddress:       EmailAddressColumn,
		FirstName:          FirstNameColumn,
		LastName:           LastNameColumn,
		TranscriptMetadata: TranscriptMetadataColumn,
		Availability:       AvailabilityColumn,
		CreatedAt:          CreatedAtColumn,
		UpdatedAt:          UpdatedAtColumn,
		DeletedAt:          DeletedAtColumn,
		AcceptedAt:         AcceptedAtColumn,
		RejectedAt:         RejectedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
