//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AuthTokens = newAuthTokensTable("auth", "auth_tokens", "")

type authTokensTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	UserID    postgres.ColumnString
	TokenHash postgres.ColumnString
	ExpiresAt postgres.ColumnTimestampz
	UsedAt    postgres.ColumnTimestampz
	CreatedAt postgres.ColumnTimestampz
	Type      postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AuthTokensTable struct {
	authTokensTable

	EXCLUDED authTokensTable
}

// AS creates new AuthTokensTable with assigned alias
func (a AuthTokensTable) AS(alias string) *AuthTokensTable {
	return newAuthTokensTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AuthTokensTable with assigned schema name
func (a AuthTokensTable) FromSchema(schemaName string) *AuthTokensTable {
	return newAuthTokensTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AuthTokensTable with assigned table prefix
func (a AuthTokensTable) WithPrefix(prefix string) *AuthTokensTable {
	return newAuthTokensTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AuthTokensTable with assigned table suffix
func (a AuthTokensTable) WithSuffix(suffix string) *AuthTokensTable {
	return newAuthTokensTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAuthTokensTable(schemaName, tableName, alias string) *AuthTokensTable {
	return &AuthTokensTable{
		authTokensTable: newAuthTokensTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newAuthTokensTableImpl("", "excluded", ""),
	}
}

func newAuthTokensTableImpl(schemaName, tableName, alias string) authTokensTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		UserIDColumn    = postgres.StringColumn("user_id")
		TokenHashColumn = postgres.StringColumn("token_hash")
		ExpiresAtColumn = postgres.TimestampzColumn("expires_at")
		UsedAtColumn    = postgres.TimestampzColumn("used_at")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		TypeColumn      = postgres.StringColumn("type")
		allColumns      = postgres.ColumnList{IDColumn, UserIDColumn, TokenHashColumn, ExpiresAtColumn, UsedAtColumn, CreatedAtColumn, TypeColumn}
		mutableColumns  = postgres.ColumnList{UserIDColumn, TokenHashColumn, ExpiresAtColumn, UsedAtColumn, CreatedAtColumn, TypeColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, CreatedAtColumn, TypeColumn}
	)

	return authTokensTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		TokenHash: TokenHashColumn,
		ExpiresAt: ExpiresAtColumn,
		UsedAt:    UsedAtColumn,
		CreatedAt: CreatedAtColumn,
		Type:      TypeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
