//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EmailVerifications = newEmailVerificationsTable("auth", "email_verifications", "")

type emailVerificationsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	UserID    postgres.ColumnString
	TokenHash postgres.ColumnString
	ExpiresAt postgres.ColumnTimestampz
	UsedAt    postgres.ColumnTimestampz
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EmailVerificationsTable struct {
	emailVerificationsTable

	EXCLUDED emailVerificationsTable
}

// AS creates new EmailVerificationsTable with assigned alias
func (a EmailVerificationsTable) AS(alias string) *EmailVerificationsTable {
	return newEmailVerificationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmailVerificationsTable with assigned schema name
func (a EmailVerificationsTable) FromSchema(schemaName string) *EmailVerificationsTable {
	return newEmailVerificationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EmailVerificationsTable with assigned table prefix
func (a EmailVerificationsTable) WithPrefix(prefix string) *EmailVerificationsTable {
	return newEmailVerificationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EmailVerificationsTable with assigned table suffix
func (a EmailVerificationsTable) WithSuffix(suffix string) *EmailVerificationsTable {
	return newEmailVerificationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEmailVerificationsTable(schemaName, tableName, alias string) *EmailVerificationsTable {
	return &EmailVerificationsTable{
		emailVerificationsTable: newEmailVerificationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newEmailVerificationsTableImpl("", "excluded", ""),
	}
}

func newEmailVerificationsTableImpl(schemaName, tableName, alias string) emailVerificationsTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		UserIDColumn    = postgres.StringColumn("user_id")
		TokenHashColumn = postgres.StringColumn("token_hash")
		ExpiresAtColumn = postgres.TimestampzColumn("expires_at")
		UsedAtColumn    = postgres.TimestampzColumn("used_at")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, UserIDColumn, TokenHashColumn, ExpiresAtColumn, UsedAtColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{UserIDColumn, TokenHashColumn, ExpiresAtColumn, UsedAtColumn, CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return emailVerificationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		TokenHash: TokenHashColumn,
		ExpiresAt: ExpiresAtColumn,
		UsedAt:    UsedAtColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
