//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var StudentBankingConsent = newStudentBankingConsentTable("auth", "student_banking_consent", "")

type studentBankingConsentTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	StudentID      postgres.ColumnInteger
	ConsentedAt    postgres.ColumnTimestampz
	ConsentVersion postgres.ColumnString
	IPAddress      postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type StudentBankingConsentTable struct {
	studentBankingConsentTable

	EXCLUDED studentBankingConsentTable
}

// AS creates new StudentBankingConsentTable with assigned alias
func (a StudentBankingConsentTable) AS(alias string) *StudentBankingConsentTable {
	return newStudentBankingConsentTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new StudentBankingConsentTable with assigned schema name
func (a StudentBankingConsentTable) FromSchema(schemaName string) *StudentBankingConsentTable {
	return newStudentBankingConsentTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new StudentBankingConsentTable with assigned table prefix
func (a StudentBankingConsentTable) WithPrefix(prefix string) *StudentBankingConsentTable {
	return newStudentBankingConsentTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new StudentBankingConsentTable with assigned table suffix
func (a StudentBankingConsentTable) WithSuffix(suffix string) *StudentBankingConsentTable {
	return newStudentBankingConsentTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newStudentBankingConsentTable(schemaName, tableName, alias string) *StudentBankingConsentTable {
	return &StudentBankingConsentTable{
		studentBankingConsentTable: newStudentBankingConsentTableImpl(schemaName, tableName, alias),
		EXCLUDED:                   newStudentBankingConsentTableImpl("", "excluded", ""),
	}
}

func newStudentBankingConsentTableImpl(schemaName, tableName, alias string) studentBankingConsentTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		StudentIDColumn      = postgres.IntegerColumn("student_id")
		ConsentedAtColumn    = postgres.TimestampzColumn("consented_at")
		ConsentVersionColumn = postgres.StringColumn("consent_version")
		IPAddressColumn      = postgres.StringColumn("ip_address")
		allColumns           = postgres.ColumnList{IDColumn, StudentIDColumn, ConsentedAtColumn, ConsentVersionColumn, IPAddressColumn}
		mutableColumns       = postgres.ColumnList{StudentIDColumn, ConsentedAtColumn, ConsentVersionColumn, IPAddressColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, ConsentedAtColumn}
	)

	return studentBankingConsentTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		StudentID:      StudentIDColumn,
		ConsentedAt:    ConsentedAtColumn,
		ConsentVersion: ConsentVersionColumn,
		IPAddress:      IPAddressColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
