import { useState, useEffect, useCallback, useRef } from 'react'
import { QRCodeSVG } from 'qrcode.react'
import { RefreshCw, Clock, QrCode, Copy, Check } from 'lucide-react'
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
    useActiveClockInCode,
    useGenerateClockInCode,
} from '@/lib/queries/time-logs'
import { useDocumentTitle } from '@/hooks/use-document-title'

const REFRESH_INTERVAL_MS = 30_000

export function ClockInStation() {
    useDocumentTitle('Clock-In Station')

    const codeQuery = useActiveClockInCode()
    const generateCode = useGenerateClockInCode()
    const [secondsLeft, setSecondsLeft] = useState(REFRESH_INTERVAL_MS / 1000)
    const [copied, setCopied] = useState(false)
    const hasAutoGenerated = useRef(false)
    const lastGeneratedAt = useRef(Date.now())

    const code = codeQuery.data

    // Auto-generate a code on mount if none exists
    useEffect(() => {
        if (codeQuery.isFetched && !code && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true
            lastGeneratedAt.current = Date.now()
            generateCode.mutate(1)
        }
    }, [codeQuery.isFetched, code]) // eslint-disable-line react-hooks/exhaustive-deps

    // Auto-refresh: generate a new code every 30s
    useEffect(() => {
        const id = setInterval(() => {
            lastGeneratedAt.current = Date.now()
            generateCode.mutate(1)
        }, REFRESH_INTERVAL_MS)
        return () => clearInterval(id)
    }, []) // eslint-disable-line react-hooks/exhaustive-deps

    // Tick the countdown to next refresh every second
    useEffect(() => {
        const id = setInterval(() => {
            const elapsed = Date.now() - lastGeneratedAt.current
            const remaining = Math.max(
                0,
                Math.ceil((REFRESH_INTERVAL_MS - elapsed) / 1000),
            )
            setSecondsLeft(remaining)
        }, 1000)
        return () => clearInterval(id)
    }, [])

    const clockUrl = code
        ? `${window.location.origin}/clock?code=${code.code}`
        : null

    const handleCopy = useCallback(() => {
        if (!clockUrl) return
        navigator.clipboard.writeText(clockUrl)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }, [clockUrl])

    const isLoading = codeQuery.isLoading || (!code && generateCode.isPending)

    return (
        <div className="mx-auto max-w-2xl space-y-6">
            <div>
                <h1 className="text-2xl font-bold tracking-tight">
                    Clock-In Station
                </h1>
                <p className="text-muted-foreground">
                    Display this QR code for students to scan and clock in to
                    their shifts.
                </p>
            </div>

            <Card>
                <CardHeader>
                    <div className="flex items-center justify-between">
                        <div>
                            <CardTitle className="flex items-center gap-2">
                                <QrCode className="h-5 w-5" />
                                QR Code
                            </CardTitle>
                            <CardDescription>
                                Students scan this to open their clock-in page
                            </CardDescription>
                        </div>
                        {code && (
                            <Badge
                                variant="outline"
                                className="gap-1.5 text-green-600"
                            >
                                <Clock className="h-3 w-3" />
                                {secondsLeft}s
                            </Badge>
                        )}
                    </div>
                </CardHeader>
                <CardContent>
                    {isLoading ? (
                        <div className="flex h-64 items-center justify-center">
                            <RefreshCw className="h-6 w-6 animate-spin text-muted-foreground" />
                        </div>
                    ) : clockUrl ? (
                        <div className="flex flex-col items-center gap-6">
                            <div className="rounded-xl border bg-white p-6">
                                <QRCodeSVG
                                    value={clockUrl}
                                    size={280}
                                    level="M"
                                    includeMargin={false}
                                />
                            </div>
                            <div className="flex flex-col items-center gap-2 text-center">
                                <p className="font-mono text-3xl font-bold tracking-[0.3em]">
                                    {code!.code}
                                </p>
                                <p className="text-sm text-muted-foreground">
                                    Or enter this code manually
                                </p>
                            </div>
                            <div className="flex gap-2">
                                <Button
                                    variant="outline"
                                    size="sm"
                                    onClick={handleCopy}
                                >
                                    {copied ? (
                                        <Check className="mr-1.5 h-3.5 w-3.5" />
                                    ) : (
                                        <Copy className="mr-1.5 h-3.5 w-3.5" />
                                    )}
                                    {copied ? 'Copied' : 'Copy link'}
                                </Button>
                            </div>
                            <p className="text-xs text-muted-foreground">
                                Code refreshes automatically every 30 seconds
                            </p>
                        </div>
                    ) : (
                        <div className="flex h-64 items-center justify-center">
                            <RefreshCw className="h-6 w-6 animate-spin text-muted-foreground" />
                        </div>
                    )}
                </CardContent>
            </Card>
        </div>
    )
}
