//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var BankAccountType = &struct {
	Chequeing postgres.StringExpression
	Savings   postgres.StringExpression
}{
	Chequeing: postgres.NewEnumValue("chequeing"),
	Savings:   postgres.NewEnumValue("savings"),
}
