//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Roles string

const (
	Roles_Student Roles = "student"
	Roles_Admin   Roles = "admin"
)

var RolesAllValues = []Roles{
	Roles_Student,
	Roles_Admin,
}

func (e *Roles) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "student":
		*e = Roles_Student
	case "admin":
		*e = Roles_Admin
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Roles enum")
	}

	return nil
}

func (e Roles) String() string {
	return string(e)
}
