//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/google/uuid"
)

type ClockInCodes struct {
	ID        uuid.UUID `sql:"primary_key"`
	Code      string
	ExpiresAt time.Time
	CreatedAt time.Time
	CreatedBy uuid.UUID
}
