//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

// Named optimizer configurations with penalty weights. Maps to Python SchedulerConfig dataclass.
type SchedulerConfigs struct {
	ID                     uuid.UUID `sql:"primary_key"`
	Name                   string
	CourseShortfallPenalty float64
	MinHoursPenalty        float64
	MaxHoursPenalty        float64
	UnderstaffedPenalty    float64
	ExtraHoursPenalty      float64
	MaxExtraPenalty        float64
	BaselineHoursTarget    int32
	SolverTimeLimit        *int32
	SolverGap              *float64
	LogSolverOutput        bool
	IsDefault              bool
	CreatedAt              time.Time
	UpdatedAt              *time.Time
}
