//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Schedules struct {
	ScheduleID           uuid.UUID `sql:"primary_key"`
	Title                string
	IsActive             bool
	Assignments          string // Scheduler output: [{assistant_id, shift_id, day_of_week, start, end}]
	AvailabilityMetadata string // Snapshot of assistant availabilities used as scheduler input: [{id, courses, availability, min_hours, max_hours}]
	CreatedAt            time.Time
	CreatedBy            uuid.UUID
	UpdatedAt            *time.Time
	ArchivedAt           *time.Time
	EffectiveFrom        time.Time
	EffectiveTo          *time.Time
	GenerationID         *uuid.UUID
	SchedulerMetadata    *string // Optimizer results: {objective_value, assistant_hours, shortfalls, solver_status}
}
