//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type TimeLogs struct {
	ID             uuid.UUID `sql:"primary_key"`
	StudentID      int32
	EntryAt        time.Time
	ExitAt         *time.Time
	CreatedAt      time.Time
	Longitude      float64
	Latitude       float64
	DistanceMeters float64 // A pre-calculated distance based on the longitude and latitude to be later used to flag suspicious entries.
}
