/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppCompleteOnboardingRouteImport } from './routes/_app/complete-onboarding'
import { Route as AppAssistantsRouteImport } from './routes/_app/assistants'
import { Route as AppApplicationsRouteImport } from './routes/_app/applications'
import { Route as AppScheduleIndexRouteImport } from './routes/_app/schedule/index'
import { Route as AppAssistantsIndexRouteImport } from './routes/_app/assistants/index'
import { Route as AppScheduleScheduleIdRouteImport } from './routes/_app/schedule/$scheduleId'
import { Route as AppAssistantsPaymentsRouteImport } from './routes/_app/assistants/payments'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppCompleteOnboardingRoute = AppCompleteOnboardingRouteImport.update({
  id: '/complete-onboarding',
  path: '/complete-onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantsRoute = AppAssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleIndexRoute = AppScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppScheduleRoute,
} as any)
const AppAssistantsIndexRoute = AppAssistantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAssistantsRoute,
} as any)
const AppScheduleScheduleIdRoute = AppScheduleScheduleIdRouteImport.update({
  id: '/$scheduleId',
  path: '/$scheduleId',
  getParentRoute: () => AppScheduleRoute,
} as any)
const AppAssistantsPaymentsRoute = AppAssistantsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppAssistantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/applications': typeof AppApplicationsRoute
  '/assistants': typeof AppAssistantsRouteWithChildren
  '/complete-onboarding': typeof AppCompleteOnboardingRoute
  '/schedule': typeof AppScheduleRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/assistants/payments': typeof AppAssistantsPaymentsRoute
  '/schedule/$scheduleId': typeof AppScheduleScheduleIdRoute
  '/assistants/': typeof AppAssistantsIndexRoute
  '/schedule/': typeof AppScheduleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/applications': typeof AppApplicationsRoute
  '/complete-onboarding': typeof AppCompleteOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/assistants/payments': typeof AppAssistantsPaymentsRoute
  '/schedule/$scheduleId': typeof AppScheduleScheduleIdRoute
  '/assistants': typeof AppAssistantsIndexRoute
  '/schedule': typeof AppScheduleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/assistants': typeof AppAssistantsRouteWithChildren
  '/_app/complete-onboarding': typeof AppCompleteOnboardingRoute
  '/_app/schedule': typeof AppScheduleRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assistants/payments': typeof AppAssistantsPaymentsRoute
  '/_app/schedule/$scheduleId': typeof AppScheduleScheduleIdRoute
  '/_app/assistants/': typeof AppAssistantsIndexRoute
  '/_app/schedule/': typeof AppScheduleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/assistants'
    | '/complete-onboarding'
    | '/schedule'
    | '/settings'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/assistants/payments'
    | '/schedule/$scheduleId'
    | '/assistants/'
    | '/schedule/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/complete-onboarding'
    | '/settings'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/assistants/payments'
    | '/schedule/$scheduleId'
    | '/assistants'
    | '/schedule'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/applications'
    | '/_app/assistants'
    | '/_app/complete-onboarding'
    | '/_app/schedule'
    | '/_app/settings'
    | '/_auth/forgot-password'
    | '/_auth/onboarding'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/assistants/payments'
    | '/_app/schedule/$scheduleId'
    | '/_app/assistants/'
    | '/_app/schedule/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complete-onboarding': {
      id: '/_app/complete-onboarding'
      path: '/complete-onboarding'
      fullPath: '/complete-onboarding'
      preLoaderRoute: typeof AppCompleteOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistants': {
      id: '/_app/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AppAssistantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule/': {
      id: '/_app/schedule/'
      path: '/'
      fullPath: '/schedule/'
      preLoaderRoute: typeof AppScheduleIndexRouteImport
      parentRoute: typeof AppScheduleRoute
    }
    '/_app/assistants/': {
      id: '/_app/assistants/'
      path: '/'
      fullPath: '/assistants/'
      preLoaderRoute: typeof AppAssistantsIndexRouteImport
      parentRoute: typeof AppAssistantsRoute
    }
    '/_app/schedule/$scheduleId': {
      id: '/_app/schedule/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/schedule/$scheduleId'
      preLoaderRoute: typeof AppScheduleScheduleIdRouteImport
      parentRoute: typeof AppScheduleRoute
    }
    '/_app/assistants/payments': {
      id: '/_app/assistants/payments'
      path: '/payments'
      fullPath: '/assistants/payments'
      preLoaderRoute: typeof AppAssistantsPaymentsRouteImport
      parentRoute: typeof AppAssistantsRoute
    }
  }
}

interface AppAssistantsRouteChildren {
  AppAssistantsPaymentsRoute: typeof AppAssistantsPaymentsRoute
  AppAssistantsIndexRoute: typeof AppAssistantsIndexRoute
}

const AppAssistantsRouteChildren: AppAssistantsRouteChildren = {
  AppAssistantsPaymentsRoute: AppAssistantsPaymentsRoute,
  AppAssistantsIndexRoute: AppAssistantsIndexRoute,
}

const AppAssistantsRouteWithChildren = AppAssistantsRoute._addFileChildren(
  AppAssistantsRouteChildren,
)

interface AppScheduleRouteChildren {
  AppScheduleScheduleIdRoute: typeof AppScheduleScheduleIdRoute
  AppScheduleIndexRoute: typeof AppScheduleIndexRoute
}

const AppScheduleRouteChildren: AppScheduleRouteChildren = {
  AppScheduleScheduleIdRoute: AppScheduleScheduleIdRoute,
  AppScheduleIndexRoute: AppScheduleIndexRoute,
}

const AppScheduleRouteWithChildren = AppScheduleRoute._addFileChildren(
  AppScheduleRouteChildren,
)

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppAssistantsRoute: typeof AppAssistantsRouteWithChildren
  AppCompleteOnboardingRoute: typeof AppCompleteOnboardingRoute
  AppScheduleRoute: typeof AppScheduleRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppAssistantsRoute: AppAssistantsRouteWithChildren,
  AppCompleteOnboardingRoute: AppCompleteOnboardingRoute,
  AppScheduleRoute: AppScheduleRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
