//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ScheduleGenerations = newScheduleGenerationsTable("schedule", "schedule_generations", "")

// Audit log for schedule generation requests.
type scheduleGenerationsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	ScheduleID      postgres.ColumnString
	ConfigID        postgres.ColumnString
	Status          postgres.ColumnString
	RequestPayload  postgres.ColumnString
	ResponsePayload postgres.ColumnString
	ErrorMessage    postgres.ColumnString
	StartedAt       postgres.ColumnTimestampz
	CompletedAt     postgres.ColumnTimestampz
	CreatedAt       postgres.ColumnTimestampz
	CreatedBy       postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ScheduleGenerationsTable struct {
	scheduleGenerationsTable

	EXCLUDED scheduleGenerationsTable
}

// AS creates new ScheduleGenerationsTable with assigned alias
func (a ScheduleGenerationsTable) AS(alias string) *ScheduleGenerationsTable {
	return newScheduleGenerationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ScheduleGenerationsTable with assigned schema name
func (a ScheduleGenerationsTable) FromSchema(schemaName string) *ScheduleGenerationsTable {
	return newScheduleGenerationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ScheduleGenerationsTable with assigned table prefix
func (a ScheduleGenerationsTable) WithPrefix(prefix string) *ScheduleGenerationsTable {
	return newScheduleGenerationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ScheduleGenerationsTable with assigned table suffix
func (a ScheduleGenerationsTable) WithSuffix(suffix string) *ScheduleGenerationsTable {
	return newScheduleGenerationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newScheduleGenerationsTable(schemaName, tableName, alias string) *ScheduleGenerationsTable {
	return &ScheduleGenerationsTable{
		scheduleGenerationsTable: newScheduleGenerationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                 newScheduleGenerationsTableImpl("", "excluded", ""),
	}
}

func newScheduleGenerationsTableImpl(schemaName, tableName, alias string) scheduleGenerationsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		ScheduleIDColumn      = postgres.StringColumn("schedule_id")
		ConfigIDColumn        = postgres.StringColumn("config_id")
		StatusColumn          = postgres.StringColumn("status")
		RequestPayloadColumn  = postgres.StringColumn("request_payload")
		ResponsePayloadColumn = postgres.StringColumn("response_payload")
		ErrorMessageColumn    = postgres.StringColumn("error_message")
		StartedAtColumn       = postgres.TimestampzColumn("started_at")
		CompletedAtColumn     = postgres.TimestampzColumn("completed_at")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		CreatedByColumn       = postgres.StringColumn("created_by")
		allColumns            = postgres.ColumnList{IDColumn, ScheduleIDColumn, ConfigIDColumn, StatusColumn, RequestPayloadColumn, ResponsePayloadColumn, ErrorMessageColumn, StartedAtColumn, CompletedAtColumn, CreatedAtColumn, CreatedByColumn}
		mutableColumns        = postgres.ColumnList{ScheduleIDColumn, ConfigIDColumn, StatusColumn, RequestPayloadColumn, ResponsePayloadColumn, ErrorMessageColumn, StartedAtColumn, CompletedAtColumn, CreatedAtColumn, CreatedByColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, StatusColumn, CreatedAtColumn}
	)

	return scheduleGenerationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		ScheduleID:      ScheduleIDColumn,
		ConfigID:        ConfigIDColumn,
		Status:          StatusColumn,
		RequestPayload:  RequestPayloadColumn,
		ResponsePayload: ResponsePayloadColumn,
		ErrorMessage:    ErrorMessageColumn,
		StartedAt:       StartedAtColumn,
		CompletedAt:     CompletedAtColumn,
		CreatedAt:       CreatedAtColumn,
		CreatedBy:       CreatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
