//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Schedules = newSchedulesTable("schedule", "schedules", "")

type schedulesTable struct {
	postgres.Table

	// Columns
	ScheduleID           postgres.ColumnString
	Title                postgres.ColumnString
	IsActive             postgres.ColumnBool
	Assignments          postgres.ColumnString // This is used to store the assignments of students for a given schedule. { [student_id:int] { [0...4]: []int } }
	AvailabilityMetadata postgres.ColumnString // This stores the availabilities that were used to generate the schedule. { [student_id:int]: map[int][]int }
	CreatedAt            postgres.ColumnTimestampz
	CreatedBy            postgres.ColumnString
	UpdatedAt            postgres.ColumnTimestampz
	ArchivedAt           postgres.ColumnTimestampz
	EffectiveFrom        postgres.ColumnDate
	EffectiveTo          postgres.ColumnDate

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SchedulesTable struct {
	schedulesTable

	EXCLUDED schedulesTable
}

// AS creates new SchedulesTable with assigned alias
func (a SchedulesTable) AS(alias string) *SchedulesTable {
	return newSchedulesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SchedulesTable with assigned schema name
func (a SchedulesTable) FromSchema(schemaName string) *SchedulesTable {
	return newSchedulesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SchedulesTable with assigned table prefix
func (a SchedulesTable) WithPrefix(prefix string) *SchedulesTable {
	return newSchedulesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SchedulesTable with assigned table suffix
func (a SchedulesTable) WithSuffix(suffix string) *SchedulesTable {
	return newSchedulesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSchedulesTable(schemaName, tableName, alias string) *SchedulesTable {
	return &SchedulesTable{
		schedulesTable: newSchedulesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newSchedulesTableImpl("", "excluded", ""),
	}
}

func newSchedulesTableImpl(schemaName, tableName, alias string) schedulesTable {
	var (
		ScheduleIDColumn           = postgres.StringColumn("schedule_id")
		TitleColumn                = postgres.StringColumn("title")
		IsActiveColumn             = postgres.BoolColumn("is_active")
		AssignmentsColumn          = postgres.StringColumn("assignments")
		AvailabilityMetadataColumn = postgres.StringColumn("availability_metadata")
		CreatedAtColumn            = postgres.TimestampzColumn("created_at")
		CreatedByColumn            = postgres.StringColumn("created_by")
		UpdatedAtColumn            = postgres.TimestampzColumn("updated_at")
		ArchivedAtColumn           = postgres.TimestampzColumn("archived_at")
		EffectiveFromColumn        = postgres.DateColumn("effective_from")
		EffectiveToColumn          = postgres.DateColumn("effective_to")
		allColumns                 = postgres.ColumnList{ScheduleIDColumn, TitleColumn, IsActiveColumn, AssignmentsColumn, AvailabilityMetadataColumn, CreatedAtColumn, CreatedByColumn, UpdatedAtColumn, ArchivedAtColumn, EffectiveFromColumn, EffectiveToColumn}
		mutableColumns             = postgres.ColumnList{TitleColumn, IsActiveColumn, AssignmentsColumn, AvailabilityMetadataColumn, CreatedAtColumn, CreatedByColumn, UpdatedAtColumn, ArchivedAtColumn, EffectiveFromColumn, EffectiveToColumn}
		defaultColumns             = postgres.ColumnList{IsActiveColumn}
	)

	return schedulesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ScheduleID:           ScheduleIDColumn,
		Title:                TitleColumn,
		IsActive:             IsActiveColumn,
		Assignments:          AssignmentsColumn,
		AvailabilityMetadata: AvailabilityMetadataColumn,
		CreatedAt:            CreatedAtColumn,
		CreatedBy:            CreatedByColumn,
		UpdatedAt:            UpdatedAtColumn,
		ArchivedAt:           ArchivedAtColumn,
		EffectiveFrom:        EffectiveFromColumn,
		EffectiveTo:          EffectiveToColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
