//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SchedulerConfigs = newSchedulerConfigsTable("schedule", "scheduler_configs", "")

// Named optimizer configurations with penalty weights. Maps to Python SchedulerConfig dataclass.
type schedulerConfigsTable struct {
	postgres.Table

	// Columns
	ID                     postgres.ColumnString
	Name                   postgres.ColumnString
	CourseShortfallPenalty postgres.ColumnFloat
	MinHoursPenalty        postgres.ColumnFloat
	MaxHoursPenalty        postgres.ColumnFloat
	UnderstaffedPenalty    postgres.ColumnFloat
	ExtraHoursPenalty      postgres.ColumnFloat
	MaxExtraPenalty        postgres.ColumnFloat
	BaselineHoursTarget    postgres.ColumnInteger
	SolverTimeLimit        postgres.ColumnInteger
	SolverGap              postgres.ColumnFloat
	LogSolverOutput        postgres.ColumnBool
	IsDefault              postgres.ColumnBool
	CreatedAt              postgres.ColumnTimestampz
	UpdatedAt              postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SchedulerConfigsTable struct {
	schedulerConfigsTable

	EXCLUDED schedulerConfigsTable
}

// AS creates new SchedulerConfigsTable with assigned alias
func (a SchedulerConfigsTable) AS(alias string) *SchedulerConfigsTable {
	return newSchedulerConfigsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SchedulerConfigsTable with assigned schema name
func (a SchedulerConfigsTable) FromSchema(schemaName string) *SchedulerConfigsTable {
	return newSchedulerConfigsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SchedulerConfigsTable with assigned table prefix
func (a SchedulerConfigsTable) WithPrefix(prefix string) *SchedulerConfigsTable {
	return newSchedulerConfigsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SchedulerConfigsTable with assigned table suffix
func (a SchedulerConfigsTable) WithSuffix(suffix string) *SchedulerConfigsTable {
	return newSchedulerConfigsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSchedulerConfigsTable(schemaName, tableName, alias string) *SchedulerConfigsTable {
	return &SchedulerConfigsTable{
		schedulerConfigsTable: newSchedulerConfigsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newSchedulerConfigsTableImpl("", "excluded", ""),
	}
}

func newSchedulerConfigsTableImpl(schemaName, tableName, alias string) schedulerConfigsTable {
	var (
		IDColumn                     = postgres.StringColumn("id")
		NameColumn                   = postgres.StringColumn("name")
		CourseShortfallPenaltyColumn = postgres.FloatColumn("course_shortfall_penalty")
		MinHoursPenaltyColumn        = postgres.FloatColumn("min_hours_penalty")
		MaxHoursPenaltyColumn        = postgres.FloatColumn("max_hours_penalty")
		UnderstaffedPenaltyColumn    = postgres.FloatColumn("understaffed_penalty")
		ExtraHoursPenaltyColumn      = postgres.FloatColumn("extra_hours_penalty")
		MaxExtraPenaltyColumn        = postgres.FloatColumn("max_extra_penalty")
		BaselineHoursTargetColumn    = postgres.IntegerColumn("baseline_hours_target")
		SolverTimeLimitColumn        = postgres.IntegerColumn("solver_time_limit")
		SolverGapColumn              = postgres.FloatColumn("solver_gap")
		LogSolverOutputColumn        = postgres.BoolColumn("log_solver_output")
		IsDefaultColumn              = postgres.BoolColumn("is_default")
		CreatedAtColumn              = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn              = postgres.TimestampzColumn("updated_at")
		allColumns                   = postgres.ColumnList{IDColumn, NameColumn, CourseShortfallPenaltyColumn, MinHoursPenaltyColumn, MaxHoursPenaltyColumn, UnderstaffedPenaltyColumn, ExtraHoursPenaltyColumn, MaxExtraPenaltyColumn, BaselineHoursTargetColumn, SolverTimeLimitColumn, SolverGapColumn, LogSolverOutputColumn, IsDefaultColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns               = postgres.ColumnList{NameColumn, CourseShortfallPenaltyColumn, MinHoursPenaltyColumn, MaxHoursPenaltyColumn, UnderstaffedPenaltyColumn, ExtraHoursPenaltyColumn, MaxExtraPenaltyColumn, BaselineHoursTargetColumn, SolverTimeLimitColumn, SolverGapColumn, LogSolverOutputColumn, IsDefaultColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns               = postgres.ColumnList{IDColumn, CourseShortfallPenaltyColumn, MinHoursPenaltyColumn, MaxHoursPenaltyColumn, UnderstaffedPenaltyColumn, ExtraHoursPenaltyColumn, MaxExtraPenaltyColumn, BaselineHoursTargetColumn, LogSolverOutputColumn, IsDefaultColumn, CreatedAtColumn}
	)

	return schedulerConfigsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                     IDColumn,
		Name:                   NameColumn,
		CourseShortfallPenalty: CourseShortfallPenaltyColumn,
		MinHoursPenalty:        MinHoursPenaltyColumn,
		MaxHoursPenalty:        MaxHoursPenaltyColumn,
		UnderstaffedPenalty:    UnderstaffedPenaltyColumn,
		ExtraHoursPenalty:      ExtraHoursPenaltyColumn,
		MaxExtraPenalty:        MaxExtraPenaltyColumn,
		BaselineHoursTarget:    BaselineHoursTargetColumn,
		SolverTimeLimit:        SolverTimeLimitColumn,
		SolverGap:              SolverGapColumn,
		LogSolverOutput:        LogSolverOutputColumn,
		IsDefault:              IsDefaultColumn,
		CreatedAt:              CreatedAtColumn,
		UpdatedAt:              UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
