//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ShiftTemplates = newShiftTemplatesTable("schedule", "shift_templates", "")

// Defines shift slots that need to be staffed. These are inputs to the scheduler.
type shiftTemplatesTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	Name          postgres.ColumnString
	DayOfWeek     postgres.ColumnInteger
	StartTime     postgres.ColumnTime
	EndTime       postgres.ColumnTime
	MinStaff      postgres.ColumnInteger
	MaxStaff      postgres.ColumnInteger
	CourseDemands postgres.ColumnString // Array of {course_code: string, tutors_required: int, weight: float}
	IsActive      postgres.ColumnBool
	CreatedAt     postgres.ColumnTimestampz
	UpdatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ShiftTemplatesTable struct {
	shiftTemplatesTable

	EXCLUDED shiftTemplatesTable
}

// AS creates new ShiftTemplatesTable with assigned alias
func (a ShiftTemplatesTable) AS(alias string) *ShiftTemplatesTable {
	return newShiftTemplatesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ShiftTemplatesTable with assigned schema name
func (a ShiftTemplatesTable) FromSchema(schemaName string) *ShiftTemplatesTable {
	return newShiftTemplatesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ShiftTemplatesTable with assigned table prefix
func (a ShiftTemplatesTable) WithPrefix(prefix string) *ShiftTemplatesTable {
	return newShiftTemplatesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ShiftTemplatesTable with assigned table suffix
func (a ShiftTemplatesTable) WithSuffix(suffix string) *ShiftTemplatesTable {
	return newShiftTemplatesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newShiftTemplatesTable(schemaName, tableName, alias string) *ShiftTemplatesTable {
	return &ShiftTemplatesTable{
		shiftTemplatesTable: newShiftTemplatesTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newShiftTemplatesTableImpl("", "excluded", ""),
	}
}

func newShiftTemplatesTableImpl(schemaName, tableName, alias string) shiftTemplatesTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		NameColumn          = postgres.StringColumn("name")
		DayOfWeekColumn     = postgres.IntegerColumn("day_of_week")
		StartTimeColumn     = postgres.TimeColumn("start_time")
		EndTimeColumn       = postgres.TimeColumn("end_time")
		MinStaffColumn      = postgres.IntegerColumn("min_staff")
		MaxStaffColumn      = postgres.IntegerColumn("max_staff")
		CourseDemandsColumn = postgres.StringColumn("course_demands")
		IsActiveColumn      = postgres.BoolColumn("is_active")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, NameColumn, DayOfWeekColumn, StartTimeColumn, EndTimeColumn, MinStaffColumn, MaxStaffColumn, CourseDemandsColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{NameColumn, DayOfWeekColumn, StartTimeColumn, EndTimeColumn, MinStaffColumn, MaxStaffColumn, CourseDemandsColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, MinStaffColumn, MaxStaffColumn, CourseDemandsColumn, IsActiveColumn, CreatedAtColumn}
	)

	return shiftTemplatesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		Name:          NameColumn,
		DayOfWeek:     DayOfWeekColumn,
		StartTime:     StartTimeColumn,
		EndTime:       EndTimeColumn,
		MinStaff:      MinStaffColumn,
		MaxStaff:      MaxStaffColumn,
		CourseDemands: CourseDemandsColumn,
		IsActive:      IsActiveColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
